# Generated by Django 4.2.29 on 2026-03-19 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('customer_type', models.CharField(choices=[('Corporate', 'Corporate'), ('SME', 'SME'), ('Individual', 'Individual'), ('Government', 'Government'), ('NGO', 'NGO')], default='Corporate', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Blacklisted', 'Blacklisted')], default='Active', max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(default='Kenya', max_length=50)),
                ('website', models.URLField(blank=True)),
                ('kra_pin', models.CharField(blank=True, max_length=20)),
                ('vat_number', models.CharField(blank=True, max_length=20)),
                ('wht_category', models.CharField(choices=[('None', 'None (No WHT)'), ('Consultancy', 'Consultancy (5%)'), ('Rent', 'Rent (10%)'), ('Contracts', 'Contracts / Supplies (3%)')], default='None', max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_terms_days', models.IntegerField(default=30)),
                ('early_payment_discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('early_payment_days', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('invoice_type', models.CharField(choices=[('Invoice', 'Tax Invoice'), ('Proforma', 'Proforma Invoice'), ('Recurring', 'Recurring Invoice'), ('Credit_Note', 'Credit Note')], default='Invoice', max_length=15)),
                ('our_ref', models.CharField(blank=True, help_text='Internal reference / PO number', max_length=50)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('service_period_start', models.DateField(blank=True, null=True)),
                ('service_period_end', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('wht_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_collected', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_interval', models.CharField(blank=True, help_text='Monthly, Quarterly, Annually', max_length=20)),
                ('next_invoice_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved — Posted to GL'), ('Sent', 'Sent to Customer'), ('Partially_Collected', 'Partially Collected'), ('Collected', 'Fully Collected'), ('Cancelled', 'Cancelled'), ('Overdue', 'Overdue')], default='Draft', max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='AR.customer')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_invoices', to='Finance.journalentry')),
            ],
            options={
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('receipt_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('M-Pesa', 'M-Pesa'), ('Cash', 'Cash')], default='Bank Transfer', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('wht_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='AR.customer')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_receipts', to='Finance.journalentry')),
            ],
            options={
                'ordering': ['-receipt_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=16, help_text='VAT rate % (default 16%)', max_digits=5)),
                ('gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finance.account')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='AR.invoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='AR.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='AR.invoice')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='Finance.journalentry')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='AR.invoice')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='AR.receipt')),
            ],
            options={
                'unique_together': {('receipt', 'invoice')},
            },
        ),
    ]
