# Generated by Django 4.2.29 on 2026-03-17 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('kra_pin', models.CharField(blank=True, max_length=20)),
                ('nssf_number', models.CharField(blank=True, max_length=20)),
                ('shif_number', models.CharField(blank=True, max_length=20)),
                ('job_title', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Intern', 'Intern')], default='Full-Time', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Terminated', 'Terminated')], default='Active', max_length=20)),
                ('date_joined', models.DateField()),
                ('date_terminated', models.DateField(blank=True, null=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('house_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance_premium', models.DecimalField(decimal_places=2, default=0, help_text='Monthly insurance premium for relief', max_digits=10)),
                ('payment_method', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('M-Pesa', 'M-Pesa'), ('Cash', 'Cash')], default='Bank Transfer', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('mpesa_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='Payroll.department')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('period_year', models.IntegerField()),
                ('period_month', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Processed', 'Processed'), ('Posted', 'Posted'), ('Void', 'Void')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_run', to='Finance.journalentry')),
            ],
            options={
                'verbose_name': 'Payroll Run',
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('period_year', 'period_month')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Final', 'Final'), ('Paid', 'Paid')], default='Draft', max_length=10)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('house_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paye', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nssf_tier1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nssf_tier2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nssf_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shif', models.DecimalField(decimal_places=2, max_digits=10)),
                ('housing_levy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employer_nssf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employer_housing', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxable_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('personal_relief', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='Payroll.employee')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='Payroll.payrollrun')),
            ],
            options={
                'ordering': ['employee__last_name'],
                'unique_together': {('run', 'employee')},
            },
        ),
    ]
