# Generated by Django 4.2.29 on 2026-03-19 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('bill_type', models.CharField(choices=[('Invoice', 'Supplier Invoice'), ('Credit_Note', 'Credit Note'), ('Debit_Note', 'Debit Note')], default='Invoice', max_length=15)),
                ('vendor_ref', models.CharField(blank=True, help_text="Vendor's own invoice number", max_length=50)),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField()),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('wht_amount', models.DecimalField(decimal_places=2, default=0, help_text='Withholding tax deducted', max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='subtotal + VAT - WHT - discount', max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted — Awaiting Procurement'), ('Approved_Procurement', 'Approved by Procurement'), ('Approved_Finance', 'Approved by Finance — Posted to GL'), ('Partially_Paid', 'Partially Paid'), ('Paid', 'Fully Paid'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Draft', max_length=25)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('procurement_approved_at', models.DateTimeField(blank=True, null=True)),
                ('finance_approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_created', to=settings.AUTH_USER_MODEL)),
                ('finance_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_finance_approved', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_bills', to='Finance.journalentry')),
                ('procurement_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_procurement_approved', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_rejected', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-bill_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('vendor_type', models.CharField(choices=[('Supplier', 'Supplier'), ('Contractor', 'Contractor'), ('Consultant', 'Consultant'), ('Utility', 'Utility'), ('Landlord', 'Landlord'), ('Other', 'Other')], default='Supplier', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Blacklisted', 'Blacklisted')], default='Active', max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(default='Kenya', max_length=50)),
                ('website', models.URLField(blank=True)),
                ('kra_pin', models.CharField(blank=True, max_length=20)),
                ('vat_number', models.CharField(blank=True, max_length=20)),
                ('wht_category', models.CharField(choices=[('None', 'None (No WHT)'), ('Consultancy', 'Consultancy / Professional Fees (5%)'), ('Rent', 'Rent (10%)'), ('Dividends', 'Dividends (5%)'), ('Contracts', 'Contracts / Supplies (3%)'), ('Imported_Svc', 'Imported Services (20%)')], default='None', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('account_name', models.CharField(blank=True, max_length=100)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Maximum credit allowed (KES)', max_digits=15)),
                ('payment_terms_days', models.IntegerField(default=30, help_text='Standard payment terms in days')),
                ('early_payment_discount_pct', models.DecimalField(decimal_places=2, default=0, help_text='Early payment discount %', max_digits=5)),
                ('early_payment_days', models.IntegerField(default=0, help_text='Days within which early discount applies')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('M-Pesa', 'M-Pesa'), ('Cash', 'Cash')], default='Bank Transfer', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('wht_deducted', models.DecimalField(decimal_places=2, default=0, help_text='WHT deducted at source', max_digits=15)),
                ('reference', models.CharField(blank=True, help_text='Bank ref, cheque number, M-Pesa code', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_payments', to='Finance.journalentry')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='AP.vendor')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, help_text='VAT rate % (e.g. 16 for 16%)', max_digits=5)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='AP.bill')),
                ('gl_account', models.ForeignKey(blank=True, help_text='GL expense account for this line', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finance.account')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='AP.vendor'),
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='AP.bill')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='AP.payment')),
            ],
            options={
                'unique_together': {('payment', 'bill')},
            },
        ),
    ]
