# Generated by Django 4.2.29 on 2026-03-19 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('assigned_to', models.CharField(blank=True, help_text='Department or employee', max_length=150)),
                ('condition', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], default='Good', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Disposed', 'Disposed'), ('Written Off', 'Written Off'), ('Idle', 'Idle')], default='Active', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Original purchase cost (KES)', max_digits=15)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, help_text='Estimated residual value (KES)', max_digits=15)),
                ('purchase_date', models.DateField()),
                ('in_service_date', models.DateField(help_text='Date depreciation begins')),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('depreciation_method', models.CharField(choices=[('SLM', 'Straight-Line Method'), ('DBM', 'Declining Balance Method')], default='SLM', max_length=5)),
                ('useful_life_months', models.IntegerField(default=60)),
                ('depreciation_rate', models.DecimalField(decimal_places=4, default=0, help_text='Annual rate for DBM (e.g. 0.25)', max_digits=5)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_depreciation_date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=150)),
                ('purchase_order', models.CharField(blank=True, max_length=50)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['asset_number'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('Preventive', 'Preventive Maintenance'), ('Corrective', 'Corrective Repair'), ('Inspection', 'Inspection'), ('Upgrade', 'Upgrade / Improvement')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vendor', models.CharField(blank=True, max_length=150)),
                ('performed_by', models.CharField(blank=True, max_length=150)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='Assets.asset')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_logs', to='Finance.journalentry')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AssetRevaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revaluation_date', models.DateField()),
                ('previous_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('previous_accumulated', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_accumulated', models.DecimalField(decimal_places=2, max_digits=15)),
                ('revaluation_amount', models.DecimalField(decimal_places=2, help_text='Positive = upward, Negative = downward', max_digits=15)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revaluations', to='Assets.asset')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_revaluations', to='Finance.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_method', models.CharField(choices=[('Sale', 'Sale'), ('Scrap', 'Scrap / Write-Off'), ('Donation', 'Donation'), ('Trade-In', 'Trade-In'), ('Theft/Loss', 'Theft or Loss')], max_length=20)),
                ('disposal_date', models.DateField()),
                ('proceeds', models.DecimalField(decimal_places=2, default=0, help_text='Cash received from disposal (KES)', max_digits=15)),
                ('book_value_at_disposal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gain_loss', models.DecimalField(decimal_places=2, help_text='Positive = gain, Negative = loss', max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disposal', to='Assets.asset')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_disposals', to='Finance.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('depreciation_method', models.CharField(choices=[('SLM', 'Straight-Line Method'), ('DBM', 'Declining Balance Method')], default='SLM', max_length=5)),
                ('default_useful_life_months', models.IntegerField(default=60, help_text='Default useful life in months')),
                ('default_depreciation_rate', models.DecimalField(decimal_places=4, default=0, help_text='Annual rate for DBM (e.g. 0.25 for 25%)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gl_accumulated_account', models.ForeignKey(blank=True, help_text='Accumulated Depreciation GL account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_categories_accumulated', to='Finance.account')),
                ('gl_asset_account', models.ForeignKey(blank=True, help_text='Fixed Assets GL account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_categories_asset', to='Finance.account')),
                ('gl_depreciation_account', models.ForeignKey(blank=True, help_text='Depreciation Expense GL account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_categories_depreciation', to='Finance.account')),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='Assets.assetcategory'),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_purchases', to='Finance.journalentry'),
        ),
        migrations.CreateModel(
            name='DepreciationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.IntegerField()),
                ('period_month', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('book_value_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('method_used', models.CharField(default='SLM', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_entries', to='Assets.asset')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciation_entries', to='Finance.journalentry')),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('asset', 'period_year', 'period_month')},
            },
        ),
    ]
